#163426619 Integrate Coveralls code coverage
andela/inception-ah-backend pull request #10
Opened 2019-01-29 20:07 UTC by ODINAKACHUKWU

#### What does this PR do?
Have coveralls to determine the level of coverage on the code base

#### Description of Task to be completed?
- install coveralls and nyc to generate test coverage reports
- add coverage ReadMe badge

#### What are the relevant pivotal tracker stories?
#163426619

2019-01-29 21:53 UTC, eokwukwe reviewed
Looks good so far

2019-01-30 07:12 UTC, Ndifreke approved these changes

2019-01-30 07:21 UTC, obasajujoshua31 requested changes

2019-01-30 07:21 UTC, obasajujoshua31 commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1",
This test scripts has not been edited, I guess Benny talked about it yesterday during our daily standups

2019-01-30 08:56 UTC, ghost reviewed
Looks good, but please fix the test script.

2019-01-30 08:58 UTC, mrkingz reviewed
Looks good. Thumbs up!

2019-02-02 21:00 UTC, closed without merging