#163651958 Setup Babel
andela/inception-ah-backend pull request #15
Opened 2019-02-01 21:16 UTC by eokwukwe

#### What does this PR do?
Setup babel for ES6+ to ES5 transpiler
#### Description of Task to be completed?
- [x] install babel
- [x] configure the project to use babel as ES6+ to ES5 transpiler
#### What are the relevant pivotal tracker stories?
[#163651958](https://www.pivotaltracker.com/story/show/163651958)

2019-02-01 21:23 UTC, benfluleck commented on package.json
> +    "build": "npm run clean && mkdir build && babel ./ --ignore 'node_modules,build,.github,.nyc_output' -s -d build",
the dir to build is called dist

2019-02-01 21:26 UTC, benfluleck commented
Please implement Babael in the codebase

2019-02-02 11:26 UTC, mrkingz commented on package.json
> +    "build": "npm run clean && mkdir build && babel ./ --ignore 'node_modules,build,.github,.nyc_output' -s -d build",
You are not following the folder structure as agreed. At this point, your index.js (entry point) and babel build should be in the server folder.

2019-02-02 12:40 UTC, benfluleck requested changes

2019-02-02 12:40 UTC, benfluleck commented on package.json
> +    "babel-plugin-transform-runtime": "^6.23.0",
please use babel 7

2019-02-04 10:36 UTC, benfluleck commented on .babelrc
> +    "@babel/transform-object-rest-spread",
Not correct plugin

2019-02-04 11:08 UTC, merged