chore(setup): add start script
andela/inception-ah-backend pull request #19
Opened 2019-02-05 12:17 UTC by mrkingz

#### What does this PR do?
 - Integrate unit testing with Travis ci 
 #### Description of Task to be completed?
 - To ensure the back end has all functionality working as intended
 #### What are the relevant pivotal tracker stories?
- [#163426617](https://www.pivotaltracker.com/n/projects/2240406/stories/163426617)

2019-02-05 18:15 UTC, benfluleck commented on package.json
> +      "dist/index.js",
why not exclude the dist folder

2019-02-05 18:22 UTC, benfluleck requested changes

2019-02-05 18:22 UTC, benfluleck commented on package.json
> +    "supertest": "^3.4.2"
Why do we have supertest and chai. Please remove one of them.

2019-02-05 18:22 UTC, benfluleck commented on package.json
>      "mocha-lcov-reporter": "^1.3.0",
What is this doing in here please uninstall

2019-02-05 18:22 UTC, benfluleck commented on server/tests/miscellaneous/connection.spec.js
> +describe("Server", () => {
`describe("Get <api>",`

2019-02-05 18:22 UTC, benfluleck commented on server/tests/miscellaneous/connection.spec.js
> +  it("should return Connection ok", done => {
This is not descriptive enough. The test should tell me exactly what it is doing?

it("should return successful connection")

2019-02-05 18:22 UTC, benfluleck commented on server/tests/miscellaneous/connection.spec.js
> +  });
space between tests

2019-02-05 18:22 UTC, benfluleck commented on server/tests/miscellaneous/connection.spec.js
> +  });
space between tests

2019-02-05 18:22 UTC, benfluleck commented on server/index.js
>  import errorhandler from "errorhandler";
What is this package doing here please remove it

2019-02-05 18:24 UTC, benfluleck commented on server/index.js
> +  .then(re => {
What is this `re`?

2019-02-06 08:42 UTC, benfluleck commented on server/index.js
> +    err.status = 500;
Why did you change this to 500

2019-02-06 12:17 UTC, Ndifreke commented on package.json
> +    "dotenv": "^6.2.0",
Don't forget to take this out as requested by @benfluleck

2019-02-06 12:55 UTC, benfluleck commented on package.json
>      "mocha-lcov-reporter": "^1.3.0",
Why is this still here ?

2019-02-06 13:31 UTC, eokwukwe reviewed
Kingsley, I thought you were told to remove files and codes that we don't need. I can still see `mongoose` in `server/configs/config.js`

2019-02-06 14:01 UTC, obasajujoshua31 reviewed
This is ok

2019-02-06 15:37 UTC, Ndifreke approved these changes
I thinks this is ready to go @benfluleck

2019-02-06 15:49 UTC, merged