#163753074 Ft signup backend
andela/inception-ah-backend pull request #31
Opened 2019-02-13 06:15 UTC by mrkingz

What does this PR do?

2019-02-13 08:39 UTC, benfluleck commented
![screenshot 2019-02-13 at 9 37 20 am](https://user-images.githubusercontent.com/26222856/52698078-11ed0000-2f73-11e9-8570-2e4c41f9b126.png)
Why is my commit still in your workflow. Please find out why it is there, Also sort out your commit message. Make sure you are following convention.  Thanks @eokwukwe

2019-02-14 17:43 UTC, benfluleck commented on server/controllers/user.js
> +        httpObj: req,
rename this variable what is httpObj

2019-02-14 18:01 UTC, benfluleck commented on server/controllers/user.js
> +      verificationUrl: generateUrl({
Why is your generateUrl method in your verification method, Let's try and separate our function logic

2019-02-14 18:01 UTC, benfluleck commented on server/controllers/user.js
> +        .concat(
Don't concat use backticks and template literals, concats are expensive operations

2019-02-14 18:01 UTC, benfluleck commented on server/controllers/user.js
> +    if (user && Object.keys(user).length > 0) {
use isEmpty lodash, Ask @Ndifreke  if you are unsure

2019-02-14 18:01 UTC, benfluleck commented on server/helpers/index.js
> +export const cleanString = (string, removeAll) => {
Do you mean sanitize? What is cleanString

2019-02-14 18:01 UTC, benfluleck commented on server/helpers/index.js
> +  let all = typeof removeAll !== "undefined" ? removeAll : true;
I don't understand what this is doing that `trim()` is not doing

2019-02-14 18:01 UTC, benfluleck commented on server/helpers/index.js
> +    options && typeof options.recursive !== "undefined"
I don't even know what this method does. getDefaults what?

2019-02-14 18:01 UTC, benfluleck commented on server/helpers/index.js
> +  const trimed = {};
Why are we trimming attributes as opposed to the normal trim

2019-02-14 18:01 UTC, benfluleck commented on server/helpers/index.js
> +      error && cleanString(process.env.NODE_ENV) === "production"
cleanString I dunno what this means

2019-02-14 18:01 UTC, benfluleck commented on server/helpers/index.js
> +const ucFirst = (skip, string, rejoin) => {
Please rename this to generateSentenceCase

2019-02-14 18:01 UTC, benfluleck commented on server/helpers/index.js
> +    return (str = skip.includes(str)
???

2019-02-14 18:01 UTC, benfluleck commented on server/helpers/index.js
> +        return (str = ucFirst(skip, item, true));
????

2019-02-14 18:01 UTC, benfluleck commented on server/helpers/index.js
> +export const ucFirstString = (string, options) => {
What is this used for?

2019-02-14 18:01 UTC, benfluleck commented on server/helpers/jwt.js
> +    if (process.env.NODE_ENV === "development") {
Please remove this line, you don't need it in here, you can set a different secret on production

2019-02-14 18:01 UTC, benfluleck commented on server/helpers/jwt.js
> +      console.log(error);
Remove this line

2019-02-14 18:01 UTC, benfluleck commented on server/middlewares/validations/validateInputs.js
> +  if (isBoolean(result)) {
remove this code, sync with @Ndifreke

2019-02-14 18:02 UTC, benfluleck commented on server/models/index.js
> +sequelize =
This work has been committed before I suggest you check your commit history

2019-02-15 07:47 UTC, eokwukwe requested changes
Please check your commit message: 
``` 
feet (Sign up): Implement user Signup/Registration
- Implement new user Signup/Registration logic
[Finishes #163753074]
```
**should be**
``` 
feat(signup): implement user signup/registration

- implement new user signup/registration logic

[Finishes #163753074]
```
You may need to review the wiki for commit messages convention.

2019-02-15 12:01 UTC, mrkingz commented on server/helpers/index.js
> +export const cleanString = (string, removeAll) => {
Yes. The method clears any trailing/leading white spaces

2019-02-15 12:07 UTC, mrkingz commented on server/helpers/index.js
> +  let all = typeof removeAll !== "undefined" ? removeAll : true;
trim() only removes trailing/leading white spaces

2019-02-19 07:08 UTC, eokwukwe requested changes
Please, I noticed that you are not generating any token for the user when they sign up. You are supposed to generate a token and send it with the response.

2019-02-19 14:30 UTC, benfluleck requested changes

2019-02-19 14:30 UTC, benfluleck commented on .eslintrc
> +    "no-return-assign": 0,
Why is this here?

2019-02-19 14:30 UTC, benfluleck commented on server/configs/config.js
>      url: process.env.DEV_DATABASE_URL,
You destructured some variables in line 5 why not destructure these as well.

2019-02-19 14:30 UTC, benfluleck commented on server/configs/config.js
> +  issuer: process.env.JWT_ISSUER,
The issuer and subject are the same why?

2019-02-19 14:30 UTC, benfluleck commented on server/controllers/user.js
> +} from "../helpers/userHelpers";
Change to `helpers/users`

2019-02-19 14:30 UTC, benfluleck commented on server/controllers/user.js
> +    const user = await database["Users"].findOne({ where: { email } });
I have told the others to import Users directly from models

2019-02-19 14:30 UTC, benfluleck commented on server/controllers/user.js
> +    const user = await User.findOne({
make this variable more descriptive like you did in line 58

2019-02-19 14:30 UTC, benfluleck commented on server/helpers/jwt.js
> +export const generateJWT = (userId, configs) => {
Why is this here is it being shared by another controller?

2019-02-19 14:30 UTC, benfluleck commented on server/helpers/userHelpers.js
> +export const capitalizeFirstChar = (string, options = {}) => {
This function is doing to much for something that just capitalizes the first character. If you can't simplify this method please leave it out

2019-02-19 14:30 UTC, benfluleck commented on server/middlewares/validations/validations.js
> +    return user && Object.keys(user).length > 0
Use the loadash.isEmpty here

2019-02-19 14:30 UTC, benfluleck commented on server/middlewares/validations/validations.js
> +const User = database["Users"];
Import User from models directly

2019-02-19 14:30 UTC, benfluleck commented on server/tests/controller/signup.spec.js
> +    password,
This should be in helper in the tests in case somebody else wants to use a test with a created user

2019-02-19 14:30 UTC, benfluleck commented on server/tests/controller/signup.spec.js
> +  return Promise.resolve({ userId, email: user.get("email") });
The variables are not descriptive enough I don't understand what is happening here

2019-02-19 14:30 UTC, benfluleck commented on server/tests/controller/user.js
> +  const user = await User.create({
What is this controller doing? IF this is a login controller label it as such

2019-02-19 14:30 UTC, benfluleck commented on server/tests/controller/user.js
> +describe("POST <API /api/v1/auth/signup>", () => {
Don't mix signin and signup tests

2019-02-19 14:30 UTC, benfluleck commented on server/tests/controller/user.js
> +describe("GET <API /api/v1/auth/verification/:token>", () => {
Create a verification controller test in the controller

2019-02-19 14:30 UTC, benfluleck commented on server/tests/miscellaneous/emails/verification/email.spec.js
> +    expect(verifyEmail[0].statusCode).to.equal(202);
you don't ned to send actual emails just check the methods.

2019-02-20 12:12 UTC, obasajujoshua31 commented on server/routes/auth.js
> +import { userSignUp, verifyUser, userLogin } from "../controllers/user";
please can you change verifyUser to like verifyUserAccount, verifyUser looks generic to me.

2019-02-20 12:13 UTC, obasajujoshua31 commented on server/tests/controller/user/signUp.spec.js
> +const { expect, assert } = chai;
can you do this from line 1. something like import chai, {expect, assert} from chai

2019-02-20 12:14 UTC, obasajujoshua31 commented on server/tests/controller/user/verification.spec.js
> +  it("should not decoded a token and throw an exception", () => {
please check this tense 'decoded'

2019-02-20 12:16 UTC, obasajujoshua31 commented on server/tests/fixtures/models/userData.js
> +  // isVerified: true,
remove this comment

2019-02-20 12:17 UTC, obasajujoshua31 commented on server/tests/models/usersModel.spec.js
>      assert.equal(createdUser.dataValues.email, user.email, "email");
please consider destructuring here

2019-02-20 12:17 UTC, obasajujoshua31 commented on server/tests/validations/user.spec.js
> +// };
please remove these comments

2019-02-20 12:26 UTC, eokwukwe requested changes

2019-02-20 12:26 UTC, eokwukwe commented on server/controllers/user.js
> +      lastName: capitalizeFirstChar(lastName, { recursive: true }),
Is it necessary to capitalize the first letter when storing it in the database? I think that can be done in the frontend when it is quite necessary.

2019-02-20 12:26 UTC, eokwukwe commented on server/helpers/jwt.js
> +export const getJWTConfigs = configs => {
Please add documentation to this function

2019-02-20 14:22 UTC, eokwukwe requested changes

2019-02-20 14:22 UTC, eokwukwe commented on server/helpers/jwt.js
> + * @param {int} userId the user id
`userId` is not an `integer` but a `string`

2019-02-20 14:22 UTC, eokwukwe commented on server/helpers/jwt.js
> + * @returns {string} the decoded token
`@returns` is not a `string` but an `object`

2019-02-20 14:22 UTC, eokwukwe commented on server/helpers/users.js
> +export const getBaseUrl = httpRequestObject => {
this can be renamed to `httpRequestOrResponseObj` since we can pass in either `request` or `response` object

2019-02-20 15:40 UTC, eokwukwe approved these changes

2019-02-20 17:29 UTC, obasajujoshua31 approved these changes

2019-02-21 10:31 UTC, ghost approved these changes

2019-02-21 11:47 UTC, ODINAKACHUKWU commented on server/middlewares/validations/validations.js
> +  try {
destructure email from `req.body`

2019-02-21 12:01 UTC, ODINAKACHUKWU requested changes

2019-02-21 12:01 UTC, ODINAKACHUKWU commented on server/models/users.js
> +    const resetUrl = `${url}/${await this.generateResetToken()}`;
This is not good practice, put this into a variable and then make a reference to it

2019-02-21 12:01 UTC, ODINAKACHUKWU commented on server/tests/validations/user.spec.js
> +const User = database["Users"];
I told you to get rid of referencing the Users tables like this

2019-02-21 12:01 UTC, ODINAKACHUKWU commented on server/tests/controller/user/resetPassword.spec.js
> +    }, 40000);
This should not happen it is too long

2019-02-21 13:01 UTC, merged