#163426629 User Create Article Feature
andela/inception-ah-backend pull request #44
Opened 2019-02-22 21:07 UTC by eokwukwe

#### What does this PR do?
User create article feature
#### Description of Task to be completed?
- [x] write an integration test for user create article feature
- [x] user can create an article
- [x] user can update and delete only their articles
- [x] user can view articles by other users
#### How should this be manually tested?
- [x] clone the repo
- [x] cd into the folder and run `npm install` to install dependencies
- [x] run `npm run test`
#### What are the relevant pivotal tracker stories?
[#163426629](https://www.pivotaltracker.com/story/show/163426629)

2019-02-26 11:18 UTC, benfluleck commented on package.json
> +    "uniqid": "^5.0.3",
This is from another commit please sort out your current branch

2019-02-26 11:29 UTC, benfluleck commented on server/controllers/article.js
> +  // const { limit, offset } = articlePagination(req.query);
Why is this comment here?

2019-02-26 11:30 UTC, benfluleck commented on server/controllers/article.js
> +      // TODO
This is not  a todo comment `/* TODO: This is where the comment should be */`

2019-02-26 12:50 UTC, Ndifreke requested changes
Can you please squash your commit message history into a single commit

2019-02-26 13:42 UTC, Ndifreke approved these changes

2019-02-26 13:42 UTC, Ndifreke approved these changes

2019-02-26 13:43 UTC, mrkingz approved these changes

2019-02-26 14:57 UTC, ghost approved these changes

2019-02-26 17:54 UTC, benfluleck commented on server/middlewares/validations/validations.js
> +  if (page && isNaN(page)) {
Please rename this to pageNumber

2019-02-26 17:54 UTC, benfluleck commented on server/middlewares/validations/validations.js
> +      message: "page can only be an Integer"
Please rename to pageNumber

2019-02-26 17:56 UTC, benfluleck requested changes
Please rename page to pageNumber as it is more descriptive

2019-02-26 18:38 UTC, eokwukwe commented on server/middlewares/validations/validations.js
> +      message: "page can only be an Integer"
Done

2019-02-26 19:19 UTC, benfluleck requested changes

2019-02-26 19:19 UTC, benfluleck commented on server/middlewares/validations/validations.js
> +      message: "page can only be an Integer"
In the message should be pageNumber as well

2019-02-26 19:19 UTC, benfluleck commented on server/middlewares/validations/validations.js
> +  if (limit && isNaN(limit)) {
Change this to pageLimit please

2019-02-26 19:19 UTC, benfluleck commented on server/middlewares/validations/validations.js
> +      message: "limit can only be an Integer"
page limit please

2019-02-26 22:37 UTC, obasajujoshua31 approved these changes

2019-02-27 08:06 UTC, benfluleck approved these changes

2019-02-27 08:07 UTC, merged