#163426613 Add ESlint configuration
andela/inception-ah-backend pull request #5
Opened 2019-01-29 05:17 UTC by mrkingz

#### What does this PR do?
Add ESlint configuration to enable linting
#### Description of Task to be completed?
Enables linting to find problematic patterns or codes that doesn’t adhere to certain style guidelines
#### What are the relevant pivotal tracker stories?
- story type - chore
- story title - Add ESlint configuration
- story id - #163426613

2019-01-31 11:16 UTC, benfluleck commented on .eslintignore
> +node_modules
No new line here

2019-01-31 11:17 UTC, benfluleck commented on .eslintrc.json
> +}
New line needed here

2019-01-31 16:43 UTC, benfluleck commented
There are too many commit messages in this PR. Please squash them

2019-02-01 20:43 UTC, eokwukwe requested changes
Edit PR message. The relevant PT story part needs to only contain the story ID and it should be made to link to the PT story.

2019-02-02 10:59 UTC, mrkingz commented on .eslintignore
> +node_modules
Fixed. Thanks

2019-02-02 14:34 UTC, benfluleck requested changes

2019-02-02 14:34 UTC, benfluleck commented on package.json
> +    "lint": "./node_modules/.bin/eslint 'server/**/*js'",
install eslint globally,  I expect `eslint '**/*js`
Why is this being done one by one. it should just be one command to fix
`    "lint:fix": "prettier-eslint '**/*js --write",`
Why is there so much consideration for json files, where are they coming from?

2019-02-02 18:08 UTC, mrkingz commented on package.json
> +    "lint": "./node_modules/.bin/eslint 'server/**/*js'",
Fixed

2019-02-02 21:23 UTC, benfluleck commented
@mrkingz  please squash and amend your  commits, there are too many

2019-02-02 21:26 UTC, benfluleck requested changes

2019-02-02 21:26 UTC, benfluleck commented on .gitignore
> +<<<<<<< HEAD
This happens when you have ignored your conflicts please fix

2019-02-02 21:26 UTC, benfluleck commented on .gitignore
> +>>>>>>> chore (Setup): configure ESlint - Add ESlint configuration [Finishes #163426613]
This should not be showing up in your branch

2019-02-03 11:35 UTC, closed without merging